onEvent('recipes', event => {
	event.remove({output: 'refinedstorage:security_card'})
	event.remove({output: 'refinedstorage:security_manager'})
	event.remove({output: 'refinedstorage:white_security_manager'})
	event.remove({output: 'refinedstorage:orange_security_manager'})
	event.remove({output: 'refinedstorage:magenta_security_manager'})
	event.remove({output: 'refinedstorage:yellow_security_manager'})
	event.remove({output: 'refinedstorage:lime_security_manager'})
	event.remove({output: 'refinedstorage:pink_security_manager'})
	event.remove({output: 'refinedstorage:gray_security_manager'})
	event.remove({output: 'refinedstorage:light_gray_security_manager'})
	event.remove({output: 'refinedstorage:cyan_security_manager'})
	event.remove({output: 'refinedstorage:purple_security_manager'})
	event.remove({output: 'refinedstorage:blue_security_manager'})
	event.remove({output: 'refinedstorage:brown_security_manager'})
	event.remove({output: 'refinedstorage:green_security_manager'})
	event.remove({output: 'refinedstorage:red_security_manager'})
	event.remove({output: 'refinedstorage:black_security_manager'})
})
